### ISSUE TITLE
gobrew version is always dev

### ISSUE THREAD

**Issue by kevincobain2000** [kevincobain2000/gobrew#123]
```
$ gobrew version
[INFO] gobrew version is dev
```

**Comment by juev** [comment]
Yep...

one more:

```
~/.gobrew/bin
 21:03:58  ❯ ./gobrew version
[INFO] gobrew version is dev

~/.gobrew/bin
 21:04:12  ❯ gobrew ls
panic: runtime error: index out of range [2] with length 0

goroutine 1 [running]:
github.com/kevincobain2000/gobrew.(*GoBrew).ListVersions(0xc000137f00)
	/home/runner/work/gobrew/gobrew/gobrew.go:149 +0x8f2
main.main()
	/home/runner/work/gobrew/gobrew/cmd/gobrew/main.go:70 +0x18a
```

**Comment by juev** [comment]
As I understand it, my changes broke everything.  And due to the fact that we do not have full tests, we did not notice this in time. :(

**Comment by juev** [comment]
I seem to have corrected the panic, but it’s not yet very clear what’s happening with the version.

**Comment by kevincobain2000** [comment]
Cool 

```
╭─pulkit.kathuria@JP-GCJKVGQK0G^M ~/git/gobrew ‹master›
╰─$ gobrew self-update
Downloading 100% |██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (5.9/5.9 MB, 9.0 MB/s)
Upgrade successful
╭─pulkit.kathuria@JP-GCJKVGQK0G^M ~/git/gobrew ‹master›
╰─$ gobrew version
[INFO] gobrew version is 1.8.9
```
