### ISSUE TITLE
404 error on Mac air laptop

### ISSUE THREAD

**Issue by gedw99** [kevincobain2000/gobrew#135]
```
curl -sLk https://raw.githubusercontent.com/kevincobain2000/gobrew/master/git.io.sh | sh
Installing gobrew from: https://github.com/kevincobain2000/gobrew/releases/latest/download/gobrew-darwin-arm64 ...

Installed successfully to: /Users/apple/.gobrew/bin/gobrew
============================

gobrew 1.9.1

Usage:

    gobrew use <version>           Install and set <version>
    gobrew ls                      Alias for list
    gobrew ls-remote               List remote versions (including rc|beta versions)

    gobrew install <version>       Only install <version> (binary from official or GOBREW_REGISTRY env)
    gobrew uninstall <version>     Uninstall <version>
    gobrew list                    List installed versions
    gobrew self-update             Self update this tool
    gobrew prune                   Uninstall all go versions except current version
    gobrew version                 Show gobrew version
    gobrew help                    Show this message

Examples:
    gobrew use 1.16                # use go version 1.16
    gobrew use 1.16.1              # use go version 1.16.1
    gobrew use 1.16rc1             # use go version 1.16rc1

    gobrew use 1.16@latest         # use go version latest of 1.16

    gobrew use 1.16@dev-latest     # use go version latest of 1.16, including rc and beta
                                   # Note: rc and beta become no longer latest upon major release

    gobrew use mod                 # use go version listed in the go.mod file
    gobrew use latest              # use go version latest available
    gobrew use dev-latest          # use go version latest avalable, including rc and beta

Installation Path:

    # Add gobrew to your ~/.bashrc or ~/.zshrc
    export PATH="$HOME/.gobrew/current/bin:$HOME/.gobrew/bin:$PATH"
    export GOROOT="$HOME/.gobrew/current/go"

============================
apple@apples-MacBook-Pro ~ % gobrew use latest
==> [Info] Fetching remote versions

==> [Error] Cannot read response: 404 Not Foundpanic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/kevincobain2000/gobrew.(*GoBrew).judgeVersion(0x14000166940?, {0x16f3774bb, 0x6})
	/home/runner/work/gobrew/gobrew/gobrew.go:437 +0x760
github.com/kevincobain2000/gobrew.(*GoBrew).Install(0x14000177e88, {0x16f3774bb?, 0x14000046768?})
	/home/runner/work/gobrew/gobrew/gobrew.go:367 +0x8c
main.main()
	/home/runner/work/gobrew/gobrew/cmd/gobrew/main.go:79 +0xfc
apple@apples-MacBook-Pro ~ % which gobrew
/Users/apple/.gobrew/bin/gobrew
apple@apples-MacBook-Pro ~ % gobrew ls                                                                               
==> [Info] Nothing installed yet. Run `gobrew use latest` to install a latest version of Go.
apple@apples-MacBook-Pro ~ % gobrew ls-remote 
==> [Info] Fetching remote versions

==> [Error] Cannot read response: 404 Not Found%    
```

**Comment by gedw99** [comment]
for now I just went with "brew install go" so I can work.

**Comment by kevincobain2000** [comment]
I think I know what’s happening. Will investigate tomorrow morning. Thanks for reporting.

**Comment by kevincobain2000** [comment]
Everything is fine, I can't reproduce the error. Probably you have an older version of `gobrew` installed.

```
╰─$ gobrew version
[INFO] gobrew version is 1.9.1
```

**Comment by gedw99** [comment]
Mhh weird 

I used the curl command in the Readme on a new laptop
